Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/vagrant/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vagrant/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/hexdump.py", line 458, in <module>
    main()
  File "/home/vagrant/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/hexdump.py", line 419, in main
    runtest(logfile=args[0])
  File "/home/vagrant/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/hexdump.py", line 333, in runtest
    bin = pkgutil.get_data('hexdump', 'data/hexfile.bin')
  File "/home/vagrant/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/pkgutil.py", line 637, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/vagrant/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/data/hexfile.bin'
